/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as OfficeRouteImport } from './routes/office'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as PrincipalRouteImport } from './routes/principal'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminFeesRouteImport } from './routes/admin.fees'
import { Route as AdminHealthRouteImport } from './routes/admin.health'
import { Route as AdminInventoryRouteImport } from './routes/admin.inventory'
import { Route as AdminParentsRouteImport } from './routes/admin.parents'
import { Route as AdminPasswordResetsRouteImport } from './routes/admin.password-resets'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminStudentsRouteImport } from './routes/admin.students'
import { Route as AdminTransportRouteImport } from './routes/admin.transport'
import { Route as OfficeIndexRouteImport } from './routes/office.index'
import { Route as OfficeAdmissionsRouteImport } from './routes/office.admissions'
import { Route as OfficeClassAssignmentRouteImport } from './routes/office.class-assignment'
import { Route as OfficeEnquiriesRouteImport } from './routes/office.enquiries'
import { Route as OfficeExpensesRouteImport } from './routes/office.expenses'
import { Route as OfficeFeesRouteImport } from './routes/office.fees'
import { Route as OfficeHealthRouteImport } from './routes/office.health'
import { Route as OfficeInventoryRouteImport } from './routes/office.inventory'
import { Route as OfficeMessagesRouteImport } from './routes/office.messages'
import { Route as OfficeNewEnquiryRouteImport } from './routes/office.new-enquiry'
import { Route as OfficeParentCredentialsRouteImport } from './routes/office.parent-credentials'
import { Route as OfficePasswordResetsRouteImport } from './routes/office.password-resets'
import { Route as OfficeReceiptsRouteImport } from './routes/office.receipts'
import { Route as OfficeReportsRouteImport } from './routes/office.reports'
import { Route as OfficeStudentsRouteImport } from './routes/office.students'
import { Route as OfficeTeacherCredentialsRouteImport } from './routes/office.teacher-credentials'
import { Route as OfficeTransportRouteImport } from './routes/office.transport'
import { Route as OfficeVisitsRouteImport } from './routes/office.visits'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as ParentAttendanceRouteImport } from './routes/parent.attendance'
import { Route as ParentChildRouteImport } from './routes/parent.child'
import { Route as ParentDiaryRouteImport } from './routes/parent.diary'
import { Route as ParentFeesRouteImport } from './routes/parent.fees'
import { Route as ParentGalleryRouteImport } from './routes/parent.gallery'
import { Route as ParentHomeworkRouteImport } from './routes/parent.homework'
import { Route as ParentLeaveRouteImport } from './routes/parent.leave'
import { Route as ParentMessagesRouteImport } from './routes/parent.messages'
import { Route as PrincipalIndexRouteImport } from './routes/principal.index'
import { Route as PrincipalCalendarRouteImport } from './routes/principal.calendar'
import { Route as PrincipalCircularsRouteImport } from './routes/principal.circulars'
import { Route as PrincipalClassesRouteImport } from './routes/principal.classes'
import { Route as PrincipalDashboardRouteImport } from './routes/principal.dashboard'
import { Route as PrincipalEventsRouteImport } from './routes/principal.events'
import { Route as PrincipalHealthRouteImport } from './routes/principal.health'
import { Route as PrincipalInventoryRouteImport } from './routes/principal.inventory'
import { Route as PrincipalReportsRouteImport } from './routes/principal.reports'
import { Route as PrincipalStudentsRouteImport } from './routes/principal.students'
import { Route as PrincipalTeachersRouteImport } from './routes/principal.teachers'
import { Route as PrincipalTransportRouteImport } from './routes/principal.transport'
import { Route as PrincipalFeesRouteImport } from './routes/principal.fees'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as TeacherActivitiesRouteImport } from './routes/teacher.activities'
import { Route as TeacherAlertsRouteImport } from './routes/teacher.alerts'
import { Route as TeacherAttendanceRouteImport } from './routes/teacher.attendance'
import { Route as TeacherDiaryRouteImport } from './routes/teacher.diary'
import { Route as TeacherGalleryRouteImport } from './routes/teacher.gallery'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher.homework'
import { Route as TeacherLeaveRequestsRouteImport } from './routes/teacher.leave-requests'
import { Route as TeacherMessagesRouteImport } from './routes/teacher.messages'
import { Route as TeacherMyClassRouteImport } from './routes/teacher.my-class'
import { Route as TeacherMySubjectsRouteImport } from './routes/teacher.my-subjects'
import { Route as TeacherProgressRouteImport } from './routes/teacher.progress'
import { Route as AdminAttendanceIndexRouteImport } from './routes/admin.attendance.index'
import { Route as AdminAttendanceStaffRouteImport } from './routes/admin.attendance.staff'
import { Route as AdminAttendanceStudentsRouteImport } from './routes/admin.attendance.students'
import { Route as AdminFeesPaymentsRouteImport } from './routes/admin.fees.payments'
import { Route as PrincipalAttendanceStaffRouteImport } from './routes/principal.attendance.staff'
import { Route as PrincipalAttendanceStudentsRouteImport } from './routes/principal.attendance.students'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficeRoute = OfficeRouteImport.update({
  id: '/office',
  path: '/office',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalRoute = PrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesRoute = AdminFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHealthRoute = AdminHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParentsRoute = AdminParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPasswordResetsRoute = AdminPasswordResetsRouteImport.update({
  id: '/password-resets',
  path: '/password-resets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStudentsRoute = AdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransportRoute = AdminTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => AdminRoute,
} as any)
const OfficeIndexRoute = OfficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeAdmissionsRoute = OfficeAdmissionsRouteImport.update({
  id: '/admissions',
  path: '/admissions',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeClassAssignmentRoute = OfficeClassAssignmentRouteImport.update({
  id: '/class-assignment',
  path: '/class-assignment',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeEnquiriesRoute = OfficeEnquiriesRouteImport.update({
  id: '/enquiries',
  path: '/enquiries',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeExpensesRoute = OfficeExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeFeesRoute = OfficeFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeHealthRoute = OfficeHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeInventoryRoute = OfficeInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeMessagesRoute = OfficeMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeNewEnquiryRoute = OfficeNewEnquiryRouteImport.update({
  id: '/new-enquiry',
  path: '/new-enquiry',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeParentCredentialsRoute = OfficeParentCredentialsRouteImport.update({
  id: '/parent-credentials',
  path: '/parent-credentials',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficePasswordResetsRoute = OfficePasswordResetsRouteImport.update({
  id: '/password-resets',
  path: '/password-resets',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeReceiptsRoute = OfficeReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeReportsRoute = OfficeReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeStudentsRoute = OfficeStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeTeacherCredentialsRoute =
  OfficeTeacherCredentialsRouteImport.update({
    id: '/teacher-credentials',
    path: '/teacher-credentials',
    getParentRoute: () => OfficeRoute,
  } as any)
const OfficeTransportRoute = OfficeTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => OfficeRoute,
} as any)
const OfficeVisitsRoute = OfficeVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => OfficeRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAttendanceRoute = ParentAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildRoute = ParentChildRouteImport.update({
  id: '/child',
  path: '/child',
  getParentRoute: () => ParentRoute,
} as any)
const ParentDiaryRoute = ParentDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => ParentRoute,
} as any)
const ParentFeesRoute = ParentFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => ParentRoute,
} as any)
const ParentGalleryRoute = ParentGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => ParentRoute,
} as any)
const ParentHomeworkRoute = ParentHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => ParentRoute,
} as any)
const ParentLeaveRoute = ParentLeaveRouteImport.update({
  id: '/leave',
  path: '/leave',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ParentRoute,
} as any)
const PrincipalIndexRoute = PrincipalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalCalendarRoute = PrincipalCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalCircularsRoute = PrincipalCircularsRouteImport.update({
  id: '/circulars',
  path: '/circulars',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalClassesRoute = PrincipalClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalDashboardRoute = PrincipalDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalEventsRoute = PrincipalEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalHealthRoute = PrincipalHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalInventoryRoute = PrincipalInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalReportsRoute = PrincipalReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalStudentsRoute = PrincipalStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalTeachersRoute = PrincipalTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalTransportRoute = PrincipalTransportRouteImport.update({
  id: '/transport',
  path: '/transport',
  getParentRoute: () => PrincipalRoute,
} as any)
const PrincipalFeesRoute = PrincipalFeesRouteImport.update({
  id: '/fees',
  path: '/fees',
  getParentRoute: () => PrincipalRoute,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherActivitiesRoute = TeacherActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAlertsRoute = TeacherAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAttendanceRoute = TeacherAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherDiaryRoute = TeacherDiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherGalleryRoute = TeacherGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLeaveRequestsRoute = TeacherLeaveRequestsRouteImport.update({
  id: '/leave-requests',
  path: '/leave-requests',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMessagesRoute = TeacherMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMyClassRoute = TeacherMyClassRouteImport.update({
  id: '/my-class',
  path: '/my-class',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherMySubjectsRoute = TeacherMySubjectsRouteImport.update({
  id: '/my-subjects',
  path: '/my-subjects',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherProgressRoute = TeacherProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => TeacherRoute,
} as any)
const AdminAttendanceIndexRoute = AdminAttendanceIndexRouteImport.update({
  id: '/attendance/',
  path: '/attendance/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceStaffRoute = AdminAttendanceStaffRouteImport.update({
  id: '/attendance/staff',
  path: '/attendance/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttendanceStudentsRoute = AdminAttendanceStudentsRouteImport.update({
  id: '/attendance/students',
  path: '/attendance/students',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeesPaymentsRoute = AdminFeesPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminFeesRoute,
} as any)
const PrincipalAttendanceStaffRoute =
  PrincipalAttendanceStaffRouteImport.update({
    id: '/attendance/staff',
    path: '/attendance/staff',
    getParentRoute: () => PrincipalRoute,
  } as any)
const PrincipalAttendanceStudentsRoute =
  PrincipalAttendanceStudentsRouteImport.update({
    id: '/attendance/students',
    path: '/attendance/students',
    getParentRoute: () => PrincipalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/office': typeof OfficeRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/principal': typeof PrincipalRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/classes': typeof AdminClassesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/fees': typeof AdminFeesRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/password-resets': typeof AdminPasswordResetsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/office/admissions': typeof OfficeAdmissionsRoute
  '/office/class-assignment': typeof OfficeClassAssignmentRoute
  '/office/enquiries': typeof OfficeEnquiriesRoute
  '/office/expenses': typeof OfficeExpensesRoute
  '/office/fees': typeof OfficeFeesRoute
  '/office/health': typeof OfficeHealthRoute
  '/office/inventory': typeof OfficeInventoryRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/new-enquiry': typeof OfficeNewEnquiryRoute
  '/office/parent-credentials': typeof OfficeParentCredentialsRoute
  '/office/password-resets': typeof OfficePasswordResetsRoute
  '/office/receipts': typeof OfficeReceiptsRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/students': typeof OfficeStudentsRoute
  '/office/teacher-credentials': typeof OfficeTeacherCredentialsRoute
  '/office/transport': typeof OfficeTransportRoute
  '/office/visits': typeof OfficeVisitsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/diary': typeof ParentDiaryRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/gallery': typeof ParentGalleryRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/leave': typeof ParentLeaveRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/principal/calendar': typeof PrincipalCalendarRoute
  '/principal/circulars': typeof PrincipalCircularsRoute
  '/principal/classes': typeof PrincipalClassesRoute
  '/principal/dashboard': typeof PrincipalDashboardRoute
  '/principal/events': typeof PrincipalEventsRoute
  '/principal/health': typeof PrincipalHealthRoute
  '/principal/inventory': typeof PrincipalInventoryRoute
  '/principal/reports': typeof PrincipalReportsRoute
  '/principal/students': typeof PrincipalStudentsRoute
  '/principal/teachers': typeof PrincipalTeachersRoute
  '/principal/transport': typeof PrincipalTransportRoute
  '/teacher/activities': typeof TeacherActivitiesRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/diary': typeof TeacherDiaryRoute
  '/teacher/gallery': typeof TeacherGalleryRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/leave-requests': typeof TeacherLeaveRequestsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/my-class': typeof TeacherMyClassRoute
  '/teacher/my-subjects': typeof TeacherMySubjectsRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/admin/': typeof AdminIndexRoute
  '/office/': typeof OfficeIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/principal/': typeof PrincipalIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/attendance/staff': typeof AdminAttendanceStaffRoute
  '/admin/attendance/students': typeof AdminAttendanceStudentsRoute
  '/admin/fees/payments': typeof AdminFeesPaymentsRoute
  '/principal/attendance/staff': typeof PrincipalAttendanceStaffRoute
  '/principal/attendance/students': typeof PrincipalAttendanceStudentsRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/fees': typeof AdminFeesRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/password-resets': typeof AdminPasswordResetsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/office/admissions': typeof OfficeAdmissionsRoute
  '/office/class-assignment': typeof OfficeClassAssignmentRoute
  '/office/enquiries': typeof OfficeEnquiriesRoute
  '/office/expenses': typeof OfficeExpensesRoute
  '/office/fees': typeof OfficeFeesRoute
  '/office/health': typeof OfficeHealthRoute
  '/office/inventory': typeof OfficeInventoryRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/new-enquiry': typeof OfficeNewEnquiryRoute
  '/office/parent-credentials': typeof OfficeParentCredentialsRoute
  '/office/password-resets': typeof OfficePasswordResetsRoute
  '/office/receipts': typeof OfficeReceiptsRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/students': typeof OfficeStudentsRoute
  '/office/teacher-credentials': typeof OfficeTeacherCredentialsRoute
  '/office/transport': typeof OfficeTransportRoute
  '/office/visits': typeof OfficeVisitsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/diary': typeof ParentDiaryRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/gallery': typeof ParentGalleryRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/leave': typeof ParentLeaveRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/principal/calendar': typeof PrincipalCalendarRoute
  '/principal/circulars': typeof PrincipalCircularsRoute
  '/principal/classes': typeof PrincipalClassesRoute
  '/principal/dashboard': typeof PrincipalDashboardRoute
  '/principal/events': typeof PrincipalEventsRoute
  '/principal/health': typeof PrincipalHealthRoute
  '/principal/inventory': typeof PrincipalInventoryRoute
  '/principal/reports': typeof PrincipalReportsRoute
  '/principal/students': typeof PrincipalStudentsRoute
  '/principal/teachers': typeof PrincipalTeachersRoute
  '/principal/transport': typeof PrincipalTransportRoute
  '/teacher/activities': typeof TeacherActivitiesRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/diary': typeof TeacherDiaryRoute
  '/teacher/gallery': typeof TeacherGalleryRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/leave-requests': typeof TeacherLeaveRequestsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/my-class': typeof TeacherMyClassRoute
  '/teacher/my-subjects': typeof TeacherMySubjectsRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/admin': typeof AdminIndexRoute
  '/office': typeof OfficeIndexRoute
  '/parent': typeof ParentIndexRoute
  '/principal': typeof PrincipalIndexRoute
  '/teacher': typeof TeacherIndexRoute
  '/admin/attendance/staff': typeof AdminAttendanceStaffRoute
  '/admin/attendance/students': typeof AdminAttendanceStudentsRoute
  '/admin/fees/payments': typeof AdminFeesPaymentsRoute
  '/principal/attendance/staff': typeof PrincipalAttendanceStaffRoute
  '/principal/attendance/students': typeof PrincipalAttendanceStudentsRoute
  '/admin/attendance': typeof AdminAttendanceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/change-password': typeof ChangePasswordRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/office': typeof OfficeRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/principal': typeof PrincipalRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/classes': typeof AdminClassesRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/fees': typeof AdminFeesRouteWithChildren
  '/admin/health': typeof AdminHealthRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/parents': typeof AdminParentsRoute
  '/admin/password-resets': typeof AdminPasswordResetsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/students': typeof AdminStudentsRoute
  '/admin/transport': typeof AdminTransportRoute
  '/office/admissions': typeof OfficeAdmissionsRoute
  '/office/class-assignment': typeof OfficeClassAssignmentRoute
  '/office/enquiries': typeof OfficeEnquiriesRoute
  '/office/expenses': typeof OfficeExpensesRoute
  '/office/fees': typeof OfficeFeesRoute
  '/office/health': typeof OfficeHealthRoute
  '/office/inventory': typeof OfficeInventoryRoute
  '/office/messages': typeof OfficeMessagesRoute
  '/office/new-enquiry': typeof OfficeNewEnquiryRoute
  '/office/parent-credentials': typeof OfficeParentCredentialsRoute
  '/office/password-resets': typeof OfficePasswordResetsRoute
  '/office/receipts': typeof OfficeReceiptsRoute
  '/office/reports': typeof OfficeReportsRoute
  '/office/students': typeof OfficeStudentsRoute
  '/office/teacher-credentials': typeof OfficeTeacherCredentialsRoute
  '/office/transport': typeof OfficeTransportRoute
  '/office/visits': typeof OfficeVisitsRoute
  '/parent/attendance': typeof ParentAttendanceRoute
  '/parent/child': typeof ParentChildRoute
  '/parent/diary': typeof ParentDiaryRoute
  '/parent/fees': typeof ParentFeesRoute
  '/parent/gallery': typeof ParentGalleryRoute
  '/parent/homework': typeof ParentHomeworkRoute
  '/parent/leave': typeof ParentLeaveRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/principal/calendar': typeof PrincipalCalendarRoute
  '/principal/circulars': typeof PrincipalCircularsRoute
  '/principal/classes': typeof PrincipalClassesRoute
  '/principal/dashboard': typeof PrincipalDashboardRoute
  '/principal/events': typeof PrincipalEventsRoute
  '/principal/health': typeof PrincipalHealthRoute
  '/principal/inventory': typeof PrincipalInventoryRoute
  '/principal/reports': typeof PrincipalReportsRoute
  '/principal/students': typeof PrincipalStudentsRoute
  '/principal/teachers': typeof PrincipalTeachersRoute
  '/principal/transport': typeof PrincipalTransportRoute
  '/teacher/activities': typeof TeacherActivitiesRoute
  '/teacher/alerts': typeof TeacherAlertsRoute
  '/teacher/attendance': typeof TeacherAttendanceRoute
  '/teacher/diary': typeof TeacherDiaryRoute
  '/teacher/gallery': typeof TeacherGalleryRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/leave-requests': typeof TeacherLeaveRequestsRoute
  '/teacher/messages': typeof TeacherMessagesRoute
  '/teacher/my-class': typeof TeacherMyClassRoute
  '/teacher/my-subjects': typeof TeacherMySubjectsRoute
  '/teacher/progress': typeof TeacherProgressRoute
  '/admin/': typeof AdminIndexRoute
  '/office/': typeof OfficeIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/principal/': typeof PrincipalIndexRoute
  '/teacher/': typeof TeacherIndexRoute
  '/admin/attendance/staff': typeof AdminAttendanceStaffRoute
  '/admin/attendance/students': typeof AdminAttendanceStudentsRoute
  '/admin/fees/payments': typeof AdminFeesPaymentsRoute
  '/principal/attendance/staff': typeof PrincipalAttendanceStaffRoute
  '/principal/attendance/students': typeof PrincipalAttendanceStudentsRoute
  '/admin/attendance/': typeof AdminAttendanceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/office'
    | '/parent'
    | '/principal'
    | '/teacher'
    | '/admin/classes'
    | '/admin/events'
    | '/admin/fees'
    | '/admin/health'
    | '/admin/inventory'
    | '/admin/parents'
    | '/admin/password-resets'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/transport'
    | '/office/admissions'
    | '/office/class-assignment'
    | '/office/enquiries'
    | '/office/expenses'
    | '/office/fees'
    | '/office/health'
    | '/office/inventory'
    | '/office/messages'
    | '/office/new-enquiry'
    | '/office/parent-credentials'
    | '/office/password-resets'
    | '/office/receipts'
    | '/office/reports'
    | '/office/students'
    | '/office/teacher-credentials'
    | '/office/transport'
    | '/office/visits'
    | '/parent/attendance'
    | '/parent/child'
    | '/parent/diary'
    | '/parent/fees'
    | '/parent/gallery'
    | '/parent/homework'
    | '/parent/leave'
    | '/parent/messages'
    | '/principal/calendar'
    | '/principal/circulars'
    | '/principal/classes'
    | '/principal/dashboard'
    | '/principal/events'
    | '/principal/health'
    | '/principal/inventory'
    | '/principal/reports'
    | '/principal/students'
    | '/principal/teachers'
    | '/principal/transport'
    | '/teacher/activities'
    | '/teacher/alerts'
    | '/teacher/attendance'
    | '/teacher/diary'
    | '/teacher/gallery'
    | '/teacher/homework'
    | '/teacher/leave-requests'
    | '/teacher/messages'
    | '/teacher/my-class'
    | '/teacher/my-subjects'
    | '/teacher/progress'
    | '/admin/'
    | '/office/'
    | '/parent/'
    | '/principal/'
    | '/teacher/'
    | '/admin/attendance/staff'
    | '/admin/attendance/students'
    | '/admin/fees/payments'
    | '/principal/attendance/staff'
    | '/principal/attendance/students'
    | '/admin/attendance/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/forgot-password'
    | '/admin/classes'
    | '/admin/events'
    | '/admin/fees'
    | '/admin/health'
    | '/admin/inventory'
    | '/admin/parents'
    | '/admin/password-resets'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/transport'
    | '/office/admissions'
    | '/office/class-assignment'
    | '/office/enquiries'
    | '/office/expenses'
    | '/office/fees'
    | '/office/health'
    | '/office/inventory'
    | '/office/messages'
    | '/office/new-enquiry'
    | '/office/parent-credentials'
    | '/office/password-resets'
    | '/office/receipts'
    | '/office/reports'
    | '/office/students'
    | '/office/teacher-credentials'
    | '/office/transport'
    | '/office/visits'
    | '/parent/attendance'
    | '/parent/child'
    | '/parent/diary'
    | '/parent/fees'
    | '/parent/gallery'
    | '/parent/homework'
    | '/parent/leave'
    | '/parent/messages'
    | '/principal/calendar'
    | '/principal/circulars'
    | '/principal/classes'
    | '/principal/dashboard'
    | '/principal/events'
    | '/principal/health'
    | '/principal/inventory'
    | '/principal/reports'
    | '/principal/students'
    | '/principal/teachers'
    | '/principal/transport'
    | '/teacher/activities'
    | '/teacher/alerts'
    | '/teacher/attendance'
    | '/teacher/diary'
    | '/teacher/gallery'
    | '/teacher/homework'
    | '/teacher/leave-requests'
    | '/teacher/messages'
    | '/teacher/my-class'
    | '/teacher/my-subjects'
    | '/teacher/progress'
    | '/admin'
    | '/office'
    | '/parent'
    | '/principal'
    | '/teacher'
    | '/admin/attendance/staff'
    | '/admin/attendance/students'
    | '/admin/fees/payments'
    | '/principal/attendance/staff'
    | '/principal/attendance/students'
    | '/admin/attendance'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/change-password'
    | '/forgot-password'
    | '/office'
    | '/parent'
    | '/principal'
    | '/teacher'
    | '/admin/classes'
    | '/admin/events'
    | '/admin/fees'
    | '/admin/health'
    | '/admin/inventory'
    | '/admin/parents'
    | '/admin/password-resets'
    | '/admin/reports'
    | '/admin/students'
    | '/admin/transport'
    | '/office/admissions'
    | '/office/class-assignment'
    | '/office/enquiries'
    | '/office/expenses'
    | '/office/fees'
    | '/office/health'
    | '/office/inventory'
    | '/office/messages'
    | '/office/new-enquiry'
    | '/office/parent-credentials'
    | '/office/password-resets'
    | '/office/receipts'
    | '/office/reports'
    | '/office/students'
    | '/office/teacher-credentials'
    | '/office/transport'
    | '/office/visits'
    | '/parent/attendance'
    | '/parent/child'
    | '/parent/diary'
    | '/parent/fees'
    | '/parent/gallery'
    | '/parent/homework'
    | '/parent/leave'
    | '/parent/messages'
    | '/principal/calendar'
    | '/principal/circulars'
    | '/principal/classes'
    | '/principal/dashboard'
    | '/principal/events'
    | '/principal/health'
    | '/principal/inventory'
    | '/principal/reports'
    | '/principal/students'
    | '/principal/teachers'
    | '/principal/transport'
    | '/teacher/activities'
    | '/teacher/alerts'
    | '/teacher/attendance'
    | '/teacher/diary'
    | '/teacher/gallery'
    | '/teacher/homework'
    | '/teacher/leave-requests'
    | '/teacher/messages'
    | '/teacher/my-class'
    | '/teacher/my-subjects'
    | '/teacher/progress'
    | '/admin/'
    | '/office/'
    | '/parent/'
    | '/principal/'
    | '/teacher/'
    | '/admin/attendance/staff'
    | '/admin/attendance/students'
    | '/admin/fees/payments'
    | '/principal/attendance/staff'
    | '/principal/attendance/students'
    | '/admin/attendance/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChangePasswordRoute: typeof ChangePasswordRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  OfficeRoute: typeof OfficeRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  PrincipalRoute: typeof PrincipalRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/office': {
      id: '/office'
      path: '/office'
      fullPath: '/office'
      preLoaderRoute: typeof OfficeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal': {
      id: '/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof PrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees': {
      id: '/admin/fees'
      path: '/fees'
      fullPath: '/admin/fees'
      preLoaderRoute: typeof AdminFeesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/health': {
      id: '/admin/health'
      path: '/health'
      fullPath: '/admin/health'
      preLoaderRoute: typeof AdminHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/parents': {
      id: '/admin/parents'
      path: '/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AdminParentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/password-resets': {
      id: '/admin/password-resets'
      path: '/password-resets'
      fullPath: '/admin/password-resets'
      preLoaderRoute: typeof AdminPasswordResetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/students': {
      id: '/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AdminStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transport': {
      id: '/admin/transport'
      path: '/transport'
      fullPath: '/admin/transport'
      preLoaderRoute: typeof AdminTransportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/office/': {
      id: '/office/'
      path: '/'
      fullPath: '/office/'
      preLoaderRoute: typeof OfficeIndexRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/admissions': {
      id: '/office/admissions'
      path: '/admissions'
      fullPath: '/office/admissions'
      preLoaderRoute: typeof OfficeAdmissionsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/class-assignment': {
      id: '/office/class-assignment'
      path: '/class-assignment'
      fullPath: '/office/class-assignment'
      preLoaderRoute: typeof OfficeClassAssignmentRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/enquiries': {
      id: '/office/enquiries'
      path: '/enquiries'
      fullPath: '/office/enquiries'
      preLoaderRoute: typeof OfficeEnquiriesRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/expenses': {
      id: '/office/expenses'
      path: '/expenses'
      fullPath: '/office/expenses'
      preLoaderRoute: typeof OfficeExpensesRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/fees': {
      id: '/office/fees'
      path: '/fees'
      fullPath: '/office/fees'
      preLoaderRoute: typeof OfficeFeesRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/health': {
      id: '/office/health'
      path: '/health'
      fullPath: '/office/health'
      preLoaderRoute: typeof OfficeHealthRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/inventory': {
      id: '/office/inventory'
      path: '/inventory'
      fullPath: '/office/inventory'
      preLoaderRoute: typeof OfficeInventoryRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/messages': {
      id: '/office/messages'
      path: '/messages'
      fullPath: '/office/messages'
      preLoaderRoute: typeof OfficeMessagesRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/new-enquiry': {
      id: '/office/new-enquiry'
      path: '/new-enquiry'
      fullPath: '/office/new-enquiry'
      preLoaderRoute: typeof OfficeNewEnquiryRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/parent-credentials': {
      id: '/office/parent-credentials'
      path: '/parent-credentials'
      fullPath: '/office/parent-credentials'
      preLoaderRoute: typeof OfficeParentCredentialsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/password-resets': {
      id: '/office/password-resets'
      path: '/password-resets'
      fullPath: '/office/password-resets'
      preLoaderRoute: typeof OfficePasswordResetsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/receipts': {
      id: '/office/receipts'
      path: '/receipts'
      fullPath: '/office/receipts'
      preLoaderRoute: typeof OfficeReceiptsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/reports': {
      id: '/office/reports'
      path: '/reports'
      fullPath: '/office/reports'
      preLoaderRoute: typeof OfficeReportsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/students': {
      id: '/office/students'
      path: '/students'
      fullPath: '/office/students'
      preLoaderRoute: typeof OfficeStudentsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/teacher-credentials': {
      id: '/office/teacher-credentials'
      path: '/teacher-credentials'
      fullPath: '/office/teacher-credentials'
      preLoaderRoute: typeof OfficeTeacherCredentialsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/transport': {
      id: '/office/transport'
      path: '/transport'
      fullPath: '/office/transport'
      preLoaderRoute: typeof OfficeTransportRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/office/visits': {
      id: '/office/visits'
      path: '/visits'
      fullPath: '/office/visits'
      preLoaderRoute: typeof OfficeVisitsRouteImport
      parentRoute: typeof OfficeRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/attendance': {
      id: '/parent/attendance'
      path: '/attendance'
      fullPath: '/parent/attendance'
      preLoaderRoute: typeof ParentAttendanceRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/child': {
      id: '/parent/child'
      path: '/child'
      fullPath: '/parent/child'
      preLoaderRoute: typeof ParentChildRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/diary': {
      id: '/parent/diary'
      path: '/diary'
      fullPath: '/parent/diary'
      preLoaderRoute: typeof ParentDiaryRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/fees': {
      id: '/parent/fees'
      path: '/fees'
      fullPath: '/parent/fees'
      preLoaderRoute: typeof ParentFeesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/gallery': {
      id: '/parent/gallery'
      path: '/gallery'
      fullPath: '/parent/gallery'
      preLoaderRoute: typeof ParentGalleryRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/homework': {
      id: '/parent/homework'
      path: '/homework'
      fullPath: '/parent/homework'
      preLoaderRoute: typeof ParentHomeworkRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/leave': {
      id: '/parent/leave'
      path: '/leave'
      fullPath: '/parent/leave'
      preLoaderRoute: typeof ParentLeaveRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/principal/': {
      id: '/principal/'
      path: '/'
      fullPath: '/principal/'
      preLoaderRoute: typeof PrincipalIndexRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/calendar': {
      id: '/principal/calendar'
      path: '/calendar'
      fullPath: '/principal/calendar'
      preLoaderRoute: typeof PrincipalCalendarRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/circulars': {
      id: '/principal/circulars'
      path: '/circulars'
      fullPath: '/principal/circulars'
      preLoaderRoute: typeof PrincipalCircularsRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/classes': {
      id: '/principal/classes'
      path: '/classes'
      fullPath: '/principal/classes'
      preLoaderRoute: typeof PrincipalClassesRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/dashboard': {
      id: '/principal/dashboard'
      path: '/dashboard'
      fullPath: '/principal/dashboard'
      preLoaderRoute: typeof PrincipalDashboardRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/events': {
      id: '/principal/events'
      path: '/events'
      fullPath: '/principal/events'
      preLoaderRoute: typeof PrincipalEventsRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/fees': {
      id: '/principal/fees'
      path: '/fees'
      fullPath: '/principal/fees'
      preLoaderRoute: typeof PrincipalFeesRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/health': {
      id: '/principal/health'
      path: '/health'
      fullPath: '/principal/health'
      preLoaderRoute: typeof PrincipalHealthRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/inventory': {
      id: '/principal/inventory'
      path: '/inventory'
      fullPath: '/principal/inventory'
      preLoaderRoute: typeof PrincipalInventoryRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/reports': {
      id: '/principal/reports'
      path: '/reports'
      fullPath: '/principal/reports'
      preLoaderRoute: typeof PrincipalReportsRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/students': {
      id: '/principal/students'
      path: '/students'
      fullPath: '/principal/students'
      preLoaderRoute: typeof PrincipalStudentsRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/teachers': {
      id: '/principal/teachers'
      path: '/teachers'
      fullPath: '/principal/teachers'
      preLoaderRoute: typeof PrincipalTeachersRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/transport': {
      id: '/principal/transport'
      path: '/transport'
      fullPath: '/principal/transport'
      preLoaderRoute: typeof PrincipalTransportRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/activities': {
      id: '/teacher/activities'
      path: '/activities'
      fullPath: '/teacher/activities'
      preLoaderRoute: typeof TeacherActivitiesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/alerts': {
      id: '/teacher/alerts'
      path: '/alerts'
      fullPath: '/teacher/alerts'
      preLoaderRoute: typeof TeacherAlertsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/attendance': {
      id: '/teacher/attendance'
      path: '/attendance'
      fullPath: '/teacher/attendance'
      preLoaderRoute: typeof TeacherAttendanceRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/diary': {
      id: '/teacher/diary'
      path: '/diary'
      fullPath: '/teacher/diary'
      preLoaderRoute: typeof TeacherDiaryRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/gallery': {
      id: '/teacher/gallery'
      path: '/gallery'
      fullPath: '/teacher/gallery'
      preLoaderRoute: typeof TeacherGalleryRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/leave-requests': {
      id: '/teacher/leave-requests'
      path: '/leave-requests'
      fullPath: '/teacher/leave-requests'
      preLoaderRoute: typeof TeacherLeaveRequestsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/messages': {
      id: '/teacher/messages'
      path: '/messages'
      fullPath: '/teacher/messages'
      preLoaderRoute: typeof TeacherMessagesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/my-class': {
      id: '/teacher/my-class'
      path: '/my-class'
      fullPath: '/teacher/my-class'
      preLoaderRoute: typeof TeacherMyClassRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/my-subjects': {
      id: '/teacher/my-subjects'
      path: '/my-subjects'
      fullPath: '/teacher/my-subjects'
      preLoaderRoute: typeof TeacherMySubjectsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/progress': {
      id: '/teacher/progress'
      path: '/progress'
      fullPath: '/teacher/progress'
      preLoaderRoute: typeof TeacherProgressRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/admin/attendance/': {
      id: '/admin/attendance/'
      path: '/attendance'
      fullPath: '/admin/attendance/'
      preLoaderRoute: typeof AdminAttendanceIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/staff': {
      id: '/admin/attendance/staff'
      path: '/attendance/staff'
      fullPath: '/admin/attendance/staff'
      preLoaderRoute: typeof AdminAttendanceStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attendance/students': {
      id: '/admin/attendance/students'
      path: '/attendance/students'
      fullPath: '/admin/attendance/students'
      preLoaderRoute: typeof AdminAttendanceStudentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fees/payments': {
      id: '/admin/fees/payments'
      path: '/payments'
      fullPath: '/admin/fees/payments'
      preLoaderRoute: typeof AdminFeesPaymentsRouteImport
      parentRoute: typeof AdminFeesRoute
    }
    '/principal/attendance/staff': {
      id: '/principal/attendance/staff'
      path: '/attendance/staff'
      fullPath: '/principal/attendance/staff'
      preLoaderRoute: typeof PrincipalAttendanceStaffRouteImport
      parentRoute: typeof PrincipalRoute
    }
    '/principal/attendance/students': {
      id: '/principal/attendance/students'
      path: '/attendance/students'
      fullPath: '/principal/attendance/students'
      preLoaderRoute: typeof PrincipalAttendanceStudentsRouteImport
      parentRoute: typeof PrincipalRoute
    }
  }
}

interface AdminFeesRouteChildren {
  AdminFeesPaymentsRoute: typeof AdminFeesPaymentsRoute
}

const AdminFeesRouteChildren: AdminFeesRouteChildren = {
  AdminFeesPaymentsRoute: AdminFeesPaymentsRoute,
}

const AdminFeesRouteWithChildren = AdminFeesRoute._addFileChildren(
  AdminFeesRouteChildren,
)

interface AdminRouteChildren {
  AdminClassesRoute: typeof AdminClassesRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFeesRoute: typeof AdminFeesRouteWithChildren
  AdminHealthRoute: typeof AdminHealthRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminParentsRoute: typeof AdminParentsRoute
  AdminPasswordResetsRoute: typeof AdminPasswordResetsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminStudentsRoute: typeof AdminStudentsRoute
  AdminTransportRoute: typeof AdminTransportRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminAttendanceStaffRoute: typeof AdminAttendanceStaffRoute
  AdminAttendanceStudentsRoute: typeof AdminAttendanceStudentsRoute
  AdminAttendanceIndexRoute: typeof AdminAttendanceIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassesRoute: AdminClassesRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFeesRoute: AdminFeesRouteWithChildren,
  AdminHealthRoute: AdminHealthRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminParentsRoute: AdminParentsRoute,
  AdminPasswordResetsRoute: AdminPasswordResetsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminStudentsRoute: AdminStudentsRoute,
  AdminTransportRoute: AdminTransportRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminAttendanceStaffRoute: AdminAttendanceStaffRoute,
  AdminAttendanceStudentsRoute: AdminAttendanceStudentsRoute,
  AdminAttendanceIndexRoute: AdminAttendanceIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface OfficeRouteChildren {
  OfficeAdmissionsRoute: typeof OfficeAdmissionsRoute
  OfficeClassAssignmentRoute: typeof OfficeClassAssignmentRoute
  OfficeEnquiriesRoute: typeof OfficeEnquiriesRoute
  OfficeExpensesRoute: typeof OfficeExpensesRoute
  OfficeFeesRoute: typeof OfficeFeesRoute
  OfficeHealthRoute: typeof OfficeHealthRoute
  OfficeInventoryRoute: typeof OfficeInventoryRoute
  OfficeMessagesRoute: typeof OfficeMessagesRoute
  OfficeNewEnquiryRoute: typeof OfficeNewEnquiryRoute
  OfficeParentCredentialsRoute: typeof OfficeParentCredentialsRoute
  OfficePasswordResetsRoute: typeof OfficePasswordResetsRoute
  OfficeReceiptsRoute: typeof OfficeReceiptsRoute
  OfficeReportsRoute: typeof OfficeReportsRoute
  OfficeStudentsRoute: typeof OfficeStudentsRoute
  OfficeTeacherCredentialsRoute: typeof OfficeTeacherCredentialsRoute
  OfficeTransportRoute: typeof OfficeTransportRoute
  OfficeVisitsRoute: typeof OfficeVisitsRoute
  OfficeIndexRoute: typeof OfficeIndexRoute
}

const OfficeRouteChildren: OfficeRouteChildren = {
  OfficeAdmissionsRoute: OfficeAdmissionsRoute,
  OfficeClassAssignmentRoute: OfficeClassAssignmentRoute,
  OfficeEnquiriesRoute: OfficeEnquiriesRoute,
  OfficeExpensesRoute: OfficeExpensesRoute,
  OfficeFeesRoute: OfficeFeesRoute,
  OfficeHealthRoute: OfficeHealthRoute,
  OfficeInventoryRoute: OfficeInventoryRoute,
  OfficeMessagesRoute: OfficeMessagesRoute,
  OfficeNewEnquiryRoute: OfficeNewEnquiryRoute,
  OfficeParentCredentialsRoute: OfficeParentCredentialsRoute,
  OfficePasswordResetsRoute: OfficePasswordResetsRoute,
  OfficeReceiptsRoute: OfficeReceiptsRoute,
  OfficeReportsRoute: OfficeReportsRoute,
  OfficeStudentsRoute: OfficeStudentsRoute,
  OfficeTeacherCredentialsRoute: OfficeTeacherCredentialsRoute,
  OfficeTransportRoute: OfficeTransportRoute,
  OfficeVisitsRoute: OfficeVisitsRoute,
  OfficeIndexRoute: OfficeIndexRoute,
}

const OfficeRouteWithChildren =
  OfficeRoute._addFileChildren(OfficeRouteChildren)

interface ParentRouteChildren {
  ParentAttendanceRoute: typeof ParentAttendanceRoute
  ParentChildRoute: typeof ParentChildRoute
  ParentDiaryRoute: typeof ParentDiaryRoute
  ParentFeesRoute: typeof ParentFeesRoute
  ParentGalleryRoute: typeof ParentGalleryRoute
  ParentHomeworkRoute: typeof ParentHomeworkRoute
  ParentLeaveRoute: typeof ParentLeaveRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAttendanceRoute: ParentAttendanceRoute,
  ParentChildRoute: ParentChildRoute,
  ParentDiaryRoute: ParentDiaryRoute,
  ParentFeesRoute: ParentFeesRoute,
  ParentGalleryRoute: ParentGalleryRoute,
  ParentHomeworkRoute: ParentHomeworkRoute,
  ParentLeaveRoute: ParentLeaveRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface PrincipalRouteChildren {
  PrincipalCalendarRoute: typeof PrincipalCalendarRoute
  PrincipalCircularsRoute: typeof PrincipalCircularsRoute
  PrincipalClassesRoute: typeof PrincipalClassesRoute
  PrincipalDashboardRoute: typeof PrincipalDashboardRoute
  PrincipalEventsRoute: typeof PrincipalEventsRoute
  PrincipalHealthRoute: typeof PrincipalHealthRoute
  PrincipalInventoryRoute: typeof PrincipalInventoryRoute
  PrincipalReportsRoute: typeof PrincipalReportsRoute
  PrincipalStudentsRoute: typeof PrincipalStudentsRoute
  PrincipalTeachersRoute: typeof PrincipalTeachersRoute
  PrincipalTransportRoute: typeof PrincipalTransportRoute
  PrincipalFeesRoute: typeof PrincipalFeesRoute
  PrincipalIndexRoute: typeof PrincipalIndexRoute
  PrincipalAttendanceStaffRoute: typeof PrincipalAttendanceStaffRoute
  PrincipalAttendanceStudentsRoute: typeof PrincipalAttendanceStudentsRoute
}

const PrincipalRouteChildren: PrincipalRouteChildren = {
  PrincipalCalendarRoute: PrincipalCalendarRoute,
  PrincipalCircularsRoute: PrincipalCircularsRoute,
  PrincipalClassesRoute: PrincipalClassesRoute,
  PrincipalDashboardRoute: PrincipalDashboardRoute,
  PrincipalEventsRoute: PrincipalEventsRoute,
  PrincipalHealthRoute: PrincipalHealthRoute,
  PrincipalInventoryRoute: PrincipalInventoryRoute,
  PrincipalReportsRoute: PrincipalReportsRoute,
  PrincipalStudentsRoute: PrincipalStudentsRoute,
  PrincipalTeachersRoute: PrincipalTeachersRoute,
  PrincipalTransportRoute: PrincipalTransportRoute,
  PrincipalFeesRoute: PrincipalFeesRoute,
  PrincipalIndexRoute: PrincipalIndexRoute,
  PrincipalAttendanceStaffRoute: PrincipalAttendanceStaffRoute,
  PrincipalAttendanceStudentsRoute: PrincipalAttendanceStudentsRoute,
}

const PrincipalRouteWithChildren = PrincipalRoute._addFileChildren(
  PrincipalRouteChildren,
)

interface TeacherRouteChildren {
  TeacherActivitiesRoute: typeof TeacherActivitiesRoute
  TeacherAlertsRoute: typeof TeacherAlertsRoute
  TeacherAttendanceRoute: typeof TeacherAttendanceRoute
  TeacherDiaryRoute: typeof TeacherDiaryRoute
  TeacherGalleryRoute: typeof TeacherGalleryRoute
  TeacherHomeworkRoute: typeof TeacherHomeworkRoute
  TeacherLeaveRequestsRoute: typeof TeacherLeaveRequestsRoute
  TeacherMessagesRoute: typeof TeacherMessagesRoute
  TeacherMyClassRoute: typeof TeacherMyClassRoute
  TeacherMySubjectsRoute: typeof TeacherMySubjectsRoute
  TeacherProgressRoute: typeof TeacherProgressRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherActivitiesRoute: TeacherActivitiesRoute,
  TeacherAlertsRoute: TeacherAlertsRoute,
  TeacherAttendanceRoute: TeacherAttendanceRoute,
  TeacherDiaryRoute: TeacherDiaryRoute,
  TeacherGalleryRoute: TeacherGalleryRoute,
  TeacherHomeworkRoute: TeacherHomeworkRoute,
  TeacherLeaveRequestsRoute: TeacherLeaveRequestsRoute,
  TeacherMessagesRoute: TeacherMessagesRoute,
  TeacherMyClassRoute: TeacherMyClassRoute,
  TeacherMySubjectsRoute: TeacherMySubjectsRoute,
  TeacherProgressRoute: TeacherProgressRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChangePasswordRoute: ChangePasswordRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  OfficeRoute: OfficeRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  PrincipalRoute: PrincipalRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
